{% set name = "fica" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fica-{{ version }}.tar.gz
  sha256: 8941e24bbfe111d8f374b434800e76417daa108caca90a815ffb124bdd1d486a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pyyaml
    - docutils
    - sphinx

test:
  imports:
    - fica
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/chrispyles/fica
  summary: User configuration manager and documenter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrispyles
